language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: lpiggott7-github
    token:
      secure: de9dd94b217a5ee6130234dad7307990a2ea55be
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
